steps:
  # Checkout source code from GitHub
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/Kavipraveen/billing_system.git']
 
  # Install Python dependencies
  #- name: 'python:3.9'  # Adjust Python version if needed
   # entrypoint: 'pip'
    #args: ['install']  # If you have a requirements.txt file

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/usecas4-ci-cd/usecase4cicd', '.']
 
  # Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/usecas4-ci-cd/usecase4cicd']
